# Generated by Django 3.2.5 on 2021-07-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='user_id',
        ),
    ]
