# Generated by Django 3.2.5 on 2021-07-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_rename_user_product_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='author',
        ),
    ]
