# Generated by Django 3.2.5 on 2021-07-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_rename_user_id_product_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='product_id',
            new_name='product_obj',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='user_id',
            new_name='user_obj',
        ),
    ]
